souffle: souffle::WriteStream Class Reference
souffle::WriteStream Class Reference abstract
#include <WriteStream.h>
Public Member Functions
template<typename T >
void writeAll (const T &relation)
template<>
void writeNext (const RamDomain *tuple)
template<typename T >
void writeSize (const T &relation)
WriteStream (const std::vector< RamTypeAttribute > &symbolMask, const SymbolTable &symbolTable, const size_t auxiliaryArity, bool summary=false)
virtual ~WriteStream ()=default
Protected Member Functions
template<typename Tuple >
void writeNext (const Tuple tuple)
virtual void writeNextTuple (const RamDomain *tuple)=0
void writeNextTupleElement (std::ostream &destination, RamTypeAttribute type, RamDomain value)
virtual void writeNullary ()=0
virtual void writeSize (std::size_t)
Protected Attributes
const size_t arity
const bool summary
const std::vector< RamTypeAttribute > & symbolMask
const SymbolTable & symbolTable
Detailed Description
Definition at line 27 of file WriteStream.h.
Constructor & Destructor Documentation
WriteStream()
souffle::WriteStream::WriteStream (const std::vector< RamTypeAttribute > & symbolMask, const SymbolTable & symbolTable, const size_t auxiliaryArity, bool summary = false) inline
Definition at line 29 of file WriteStream.h.
             : symbolMask(symbolMask), symbolTable(symbolTable), summary(summary),
               arity(symbolMask.size() - auxiliaryArity) {}
~WriteStream()
virtual souffle::WriteStream::~WriteStream () virtual default
Referenced by writeSize().
Member Function Documentation
writeAll()
template<typename T > void souffle::WriteStream::writeAll (const T & relation) inline
Definition at line 34 of file WriteStream.h.
References souffle::SymbolTable::acquireLock(), arity, summary, symbolTable, writeNext(), writeNullary(), and writeSize().
{
         if (summary) {
             return writeSize(relation.size());
         }
         auto lease = symbolTable.acquireLock();
         (void)lease;
         if (arity == 0) {
             if (relation.begin() != relation.end()) {
                 writeNullary();
             }
             return;
         }
         for (const auto& current : relation) {
             writeNext(current);
         }
     }
writeNext() [1/2]
template<typename Tuple > void souffle::WriteStream::writeNext (const Tuple tuple) inline protected
Definition at line 69 of file WriteStream.h.
References writeNextTuple().
Referenced by writeAll().
{
         writeNextTuple(tuple.data);
     }
writeNext() [2/2]
template<> void souffle::WriteStream::writeNext (const RamDomain * tuple) inline
Definition at line 102 of file WriteStream.h.
References writeNextTuple().
{
     writeNextTuple(tuple);
 }
writeNextTuple()
virtual void souffle::WriteStream::writeNextTuple (const RamDomain * tuple) protected pure virtual
Implemented in souffle::WriteCoutPrintSize, souffle::WriteCoutCSV, souffle::WriteFileCSV, and souffle::WriteStreamSQLite.
Referenced by writeNext().
writeNextTupleElement()
void souffle::WriteStream::writeNextTupleElement (std::ostream & destination, RamTypeAttribute type, RamDomain value) inline protected
Definition at line 72 of file WriteStream.h.
References souffle::Float, souffle::Record, souffle::Signed, souffle::Symbol, souffle::SymbolTable::unsafeResolve(), and souffle::Unsigned.
{
         switch (type) {
             case RamTypeAttribute::Symbol:
                 destination << symbolTable.unsafeResolve(value);
                 break;
             case RamTypeAttribute::Signed:
                 destination << value;
                 break;
             case RamTypeAttribute::Unsigned:
                 destination << ramBitCast<RamUnsigned>(value);
                 break;
             case RamTypeAttribute::Float:
                 destination << ramBitCast<RamFloat>(value);
                 break;
             case RamTypeAttribute::Record:
                 assert(false && "Record writing is not supported");
         }
     }
writeNullary()
virtual void souffle::WriteStream::writeNullary () protected pure virtual
Implemented in souffle::WriteCoutPrintSize, souffle::WriteCoutCSV, souffle::WriteFileCSV, and souffle::WriteStreamSQLite.
Referenced by writeAll().
writeSize() [1/2]
template<typename T > void souffle::WriteStream::writeSize (const T & relation) inline
Definition at line 51 of file WriteStream.h.
References ~WriteStream().
Referenced by writeAll().
{
         writeSize(relation.size());
     }
writeSize() [2/2]
virtual void souffle::WriteStream::writeSize (std::size_t) inline protected virtual
Reimplemented in souffle::WriteCoutPrintSize.
Definition at line 65 of file WriteStream.h.
{
         assert(false && "attempting to print size of a write operation");
     }
Field Documentation
arity
const size_t souffle::WriteStream::arity protected
Definition at line 61 of file WriteStream.h.
Referenced by souffle::WriteStreamSQLite::createRelationTable(), souffle::WriteStreamSQLite::createRelationView(), souffle::WriteStreamSQLite::prepareInsertStatement(), writeAll(), and souffle::WriteStreamSQLite::writeNextTuple().
summary
const bool souffle::WriteStream::summary protected
Definition at line 60 of file WriteStream.h.
Referenced by writeAll().
symbolMask
const std::vector<RamTypeAttribute>& souffle::WriteStream::symbolMask protected
Definition at line 58 of file WriteStream.h.
Referenced by souffle::WriteStreamSQLite::createRelationView(), souffle::WriteSQLiteFactory::getWriter(), and souffle::WriteStreamSQLite::writeNextTuple().
symbolTable
const SymbolTable& souffle::WriteStream::symbolTable protected
Definition at line 59 of file WriteStream.h.
Referenced by souffle::WriteStreamSQLite::getSymbolTableID(), souffle::WriteStreamSQLite::getSymbolTableIDFromDB(), souffle::WriteSQLiteFactory::getWriter(), and writeAll().
The documentation for this class was generated from the following file:
WriteStream.h