souffle: souffle::PolymorphicOperatorsTransformer Class Reference
souffle::PolymorphicOperatorsTransformer Class Reference
Transformation pass to determine operator types for polymorphic operators.
#include <AstTransforms.h>
Public Member Functions
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Transformation pass to determine operator types for polymorphic operators.
Operators = Functors (plus, minus...) ∪ binary constraints (>, ≥ ...)
Definition at line 564 of file AstTransforms.h.
Member Function Documentation
getName()
std::string souffle::PolymorphicOperatorsTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 566 of file AstTransforms.h.
References souffle::ResolveAliasesTransformer::transform().
{
         return "PolymorphicOperatorsTransformer";
     }
transform()
bool souffle::PolymorphicOperatorsTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 1223 of file AstTransforms.cpp.
References souffle::all_of(), souffle::AstProgram::apply(), souffle::convertOverloadedConstraint(), souffle::convertOverloadedFunctor(), souffle::Float, souffle::AstTranslationUnit::getAnalysis(), souffle::AstTranslationUnit::getErrorReport(), souffle::AstTranslationUnit::getProgram(), souffle::TypeAnalysis::getTypes(), souffle::isFloatType(), souffle::isOverloaded(), souffle::isOverloadedFunctor(), souffle::isUnsignedType(), and souffle::Unsigned.
{
     struct TypeRewriter : public AstNodeMapper {
         mutable bool changed{false};
         const TypeAnalysis& typeAnalysis;
         ErrorReport& report;
         TypeRewriter(const TypeAnalysis& typeAnalysis, ErrorReport& report)
                 : typeAnalysis(typeAnalysis), report(report) {}
         std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
             // Utility lambdas to determine if all args are of the same type.
             auto isFloat = [&](const AstArgument* argument) {
                 return isFloatType(typeAnalysis.getTypes(argument));
             };
             auto isUnsigned = [&](const AstArgument* argument) {
                 return isUnsignedType(typeAnalysis.getTypes(argument));
             };
             // rewrite sub-expressions first
             node->apply(*this);
             // Handle functor
             if (auto* functor = dynamic_cast<AstIntrinsicFunctor*>(node.get())) {
                 if (isOverloadedFunctor(functor->getFunction())) {
                     // All args must be of the same type.
                     if (all_of(functor->getArguments(), isFloat)) {
                         FunctorOp convertedFunctor =
                                 convertOverloadedFunctor(functor->getFunction(), RamTypeAttribute::Float);
                         functor->setFunction(convertedFunctor);
                         changed = true;
                     } else if (all_of(functor->getArguments(), isUnsigned)) {
                         FunctorOp convertedFunctor =
                                 convertOverloadedFunctor(functor->getFunction(), RamTypeAttribute::Unsigned);
                         functor->setFunction(convertedFunctor);
                         changed = true;
                     }
                 }
             }
             // Handle binary constraint
             if (auto* binaryConstraint = dynamic_cast<AstBinaryConstraint*>(node.get())) {
                 if (isOverloaded(binaryConstraint->getOperator())) {
                     // Get arguments
                     auto* leftArg = binaryConstraint->getLHS();
                     auto* rightArg = binaryConstraint->getRHS();
                     // Both args must be of the same type
                     if (isFloat(leftArg) && isFloat(rightArg)) {
                         BinaryConstraintOp convertedConstraint = convertOverloadedConstraint(
                                 binaryConstraint->getOperator(), RamTypeAttribute::Float);
                         binaryConstraint->setOperator(convertedConstraint);
                         changed = true;
                     } else if (isUnsigned(leftArg) && isUnsigned(rightArg)) {
                         BinaryConstraintOp convertedConstraint = convertOverloadedConstraint(
                                 binaryConstraint->getOperator(), RamTypeAttribute::Unsigned);
                         binaryConstraint->setOperator(convertedConstraint);
                         changed = true;
                     }
                 }
             }
             // otherwise, return the original node
             return node;
         }
     };
     const TypeAnalysis& typeAnalysis = *translationUnit.getAnalysis<TypeAnalysis>();
     TypeRewriter update(typeAnalysis, translationUnit.getErrorReport());
     translationUnit.getProgram()->apply(update);
     return update.changed;
 }
The documentation for this class was generated from the following files:
AstTransforms.h
AstTransforms.cpp