souffle: souffle::AstIO Class Reference
souffle::AstIO Class Reference
Intermediate representation of IO operations.
#include <AstIO.h>
Public Member Functions
void addKVP (const std::string &key, const std::string &value)
Add kvp.
void addName (const AstRelationIdentifier &name)
Set kvp map name.
AstIO (const AstIO &io)
AstIO ()=default
AstIO * clone () const override
Create a clone (i.e.
const std::map< std::string, std::string > & getIODirectiveMap () const
Get IO directive map.
const AstRelationIdentifier & getName () const
Return the name of this kvp map.
const std::set< AstRelationIdentifier > & getNames () const
Return the names of this kvp map.
void print (std::ostream &os) const override
Output to a given output stream.
void setName (const AstRelationIdentifier &name)
Set kvp map name.
std::string unescape (const std::string &inputString) const
std::string unescape (const std::string &inputString, const std::string &needle, const std::string &replacement) const
Public Member Functions inherited from souffle::AstNode
virtual void apply (const AstNodeMapper &mapper)
Apply the mapper to all child nodes.
AstNode ()=default
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const AstNode * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
Protected Attributes
std::map< std::string, std::string > kvps
kvp map
std::set< AstRelationIdentifier > names
Name of the kvp.
Detailed Description
Intermediate representation of IO operations.
Definition at line 31 of file AstIO.h.
Constructor & Destructor Documentation
AstIO() [1/2]
souffle::AstIO::AstIO (const AstIO & io) inline
Definition at line 33 of file AstIO.h.
References AstIO().
 : names(io.names), kvps(io.kvps) {}
AstIO() [2/2]
souffle::AstIO::AstIO () default
Referenced by AstIO(), and clone().
Member Function Documentation
addKVP()
void souffle::AstIO::addKVP (const std::string & key, const std::string & value) inline
Add kvp.
Definition at line 82 of file AstIO.h.
References kvps, and unescape().
Referenced by souffle::AstPrintSize::AstPrintSize().
{
         kvps[key] = unescape(value);
     }
addName()
void souffle::AstIO::addName (const AstRelationIdentifier & name) inline
Set kvp map name.
Definition at line 72 of file AstIO.h.
References names.
{
         names.insert(name);
     }
clone()
AstIO* souffle::AstIO::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::AstNode.
Reimplemented in souffle::AstPrintSize, souffle::AstLoad, and souffle::AstStore.
Definition at line 91 of file AstIO.h.
References AstIO(), souffle::AstNode::getSrcLoc(), kvps, and names.
{
         auto res = new AstIO();
         res->names = names;
         res->kvps = kvps;
         res->setSrcLoc(getSrcLoc());
         return res;
     }
equal()
bool souffle::AstIO::equal (const AstNode & other) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 119 of file AstIO.h.
References kvps, and names.
{
         assert(nullptr != dynamic_cast<const AstIO*>(&node));
         const auto& other = static_cast<const AstIO&>(node);
         return other.names == names && other.kvps == kvps;
     }
getIODirectiveMap()
const std::map<std::string, std::string>& souffle::AstIO::getIODirectiveMap () const inline
Get IO directive map.
Definition at line 87 of file AstIO.h.
References kvps.
Referenced by souffle::MagicSetTransformer::transform().
{
         return kvps;
     }
getName()
const AstRelationIdentifier& souffle::AstIO::getName () const inline
Return the name of this kvp map.
Definition at line 62 of file AstIO.h.
References names.
Referenced by souffle::MagicSetTransformer::transform().
{
         return *names.begin();
     }
getNames()
const std::set<AstRelationIdentifier>& souffle::AstIO::getNames () const inline
Return the names of this kvp map.
Definition at line 67 of file AstIO.h.
References names.
Referenced by print().
{
         return names;
     }
print()
void souffle::AstIO::print (std::ostream & os) const inline override virtual
Output to a given output stream.
Implements souffle::AstNode.
Reimplemented in souffle::AstPrintSize, souffle::AstLoad, and souffle::AstStore.
Definition at line 35 of file AstIO.h.
References getNames(), and kvps.
Referenced by souffle::AstStore::print(), souffle::AstLoad::print(), and souffle::AstPrintSize::print().
{
         bool first = true;
         for (auto& relationName : getNames()) {
             if (first) {
                 first = false;
             } else {
                 os << ',';
             }
             os << relationName;
         }
         if (kvps.empty()) {
             return;
         }
         os << "(";
         first = true;
         for (auto& pair : kvps) {
             if (first) {
                 first = false;
             } else {
                 os << ',';
             }
             os << pair.first << "=\"" << pair.second << "\"";
         }
         os << ')';
     }
setName()
void souffle::AstIO::setName (const AstRelationIdentifier & name) inline
Set kvp map name.
Definition at line 76 of file AstIO.h.
References names.
{
         names.clear();
         names.insert(name);
     }
unescape() [1/2]
std::string souffle::AstIO::unescape (const std::string & inputString) const inline
Definition at line 99 of file AstIO.h.
Referenced by addKVP().
{
         std::string unescaped = unescape(inputString, "\\\"", "\"");
         unescaped = unescape(unescaped, "\\t", "\t");
         unescaped = unescape(unescaped, "\\r", "\r");
         unescaped = unescape(unescaped, "\\n", "\n");
         return unescaped;
     }
unescape() [2/2]
std::string souffle::AstIO::unescape (const std::string & inputString, const std::string & needle, const std::string & replacement) const inline
Definition at line 107 of file AstIO.h.
{
         std::string result = inputString;
         size_t pos = 0;
         while ((pos = result.find(needle, pos)) != std::string::npos) {
             result = result.replace(pos, needle.length(), replacement);
             pos += replacement.length();
         }
         return result;
     }
Field Documentation
kvps
std::map<std::string, std::string> souffle::AstIO::kvps protected
kvp map
Definition at line 129 of file AstIO.h.
Referenced by addKVP(), clone(), souffle::AstStore::clone(), souffle::AstLoad::clone(), souffle::AstPrintSize::clone(), equal(), getIODirectiveMap(), and print().
names
std::set<AstRelationIdentifier> souffle::AstIO::names protected
Name of the kvp.
Definition at line 126 of file AstIO.h.
Referenced by addName(), clone(), souffle::AstStore::clone(), souffle::AstLoad::clone(), souffle::AstPrintSize::clone(), equal(), getName(), getNames(), and setName().
The documentation for this class was generated from the following file:
AstIO.h