souffle: souffle::AstAtom Class Reference
souffle::AstAtom Class Reference
Subclass of Literal that represents the use of a relation either in the head or in the body of a Clause, e.g., parent(x,y).
#include <AstLiteral.h>
Public Member Functions
void addArgument (std::unique_ptr< AstArgument > arg)
Add argument to the atom.
void apply (const AstNodeMapper &map) override
Apply the mapper to all child nodes.
size_t argSize () const
Return the number of arguments.
AstAtom (AstRelationIdentifier name=AstRelationIdentifier())
AstAtom * clone () const override
Creates a clone of this AST sub-structure.
AstArgument * getArgument (size_t idx) const
Return the i-th argument of the atom.
std::vector< AstArgument * > getArguments () const
Provides access to the list of arguments of this atom.
size_t getArity () const
Return the arity of the atom.
const AstAtom * getAtom () const override
Returns this class as the referenced atom.
std::vector< const AstNode * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
const AstRelationIdentifier & getName () const
Return the name of this atom.
void print (std::ostream &os) const override
Output to a given output stream.
void setArgument (size_t idx, std::unique_ptr< AstArgument > newArg)
Replace the argument at the given index with the given argument.
void setName (const AstRelationIdentifier &n)
Set atom name.
Public Member Functions inherited from souffle::AstNode
AstNode ()=default
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
Protected Attributes
std::vector< std::unique_ptr< AstArgument > > arguments
Arguments of the atom.
AstRelationIdentifier name
Name of the atom.
Detailed Description
Subclass of Literal that represents the use of a relation either in the head or in the body of a Clause, e.g., parent(x,y).
The arguments of the atom can be variables or constants.
Definition at line 48 of file AstLiteral.h.
Constructor & Destructor Documentation
AstAtom()
souffle::AstAtom::AstAtom (AstRelationIdentifier name = AstRelationIdentifier()) inline
Definition at line 50 of file AstLiteral.h.
Referenced by clone().
 : name(std::move(name)) {}
Member Function Documentation
addArgument()
void souffle::AstAtom::addArgument (std::unique_ptr< AstArgument > arg) inline
Add argument to the atom.
Definition at line 73 of file AstLiteral.h.
References arguments.
Referenced by souffle::AstSemanticChecker::checkWitnessProblem(), and souffle::transformEqrelRelation().
{
         arguments.push_back(std::move(arg));
     }
apply()
void souffle::AstAtom::apply (const AstNodeMapper & mapper) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::AstNode.
Definition at line 122 of file AstLiteral.h.
References arguments.
{
         for (auto& arg : arguments) {
             arg = map(std::move(arg));
         }
     }
argSize()
size_t souffle::AstAtom::argSize () const inline
Return the number of arguments.
Definition at line 93 of file AstLiteral.h.
References arguments.
Referenced by souffle::AstSemanticChecker::checkFact(), and souffle::AstTranslator::ClauseTranslator::translateClause().
{
         return arguments.size();
     }
clone()
AstAtom* souffle::AstAtom::clone () const inline override virtual
Creates a clone of this AST sub-structure.
Implements souffle::AstLiteral.
Definition at line 113 of file AstLiteral.h.
References arguments, AstAtom(), souffle::AstNode::getSrcLoc(), and name.
Referenced by souffle::AstConstraint::getAtom(), souffle::getInlinedAtom(), souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::negateLiteral(), souffle::PartitionBodyLiteralsTransformer::transform(), and souffle::AstTranslator::translateRecursiveRelation().
{
         auto res = new AstAtom(name);
         res->setSrcLoc(getSrcLoc());
         for (const auto& cur : arguments) {
             res->arguments.emplace_back(cur->clone());
         }
         return res;
     }
equal()
bool souffle::AstAtom::equal (const AstNode & other) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 137 of file AstLiteral.h.
References arguments, souffle::equal_targets(), and name.
{
         assert(nullptr != dynamic_cast<const AstAtom*>(&node));
         const auto& other = static_cast<const AstAtom&>(node);
         return name == other.name && equal_targets(arguments, other.arguments);
     }
getArgument()
AstArgument* souffle::AstAtom::getArgument (size_t idx) const inline
Return the i-th argument of the atom.
Definition at line 78 of file AstLiteral.h.
References arguments.
Referenced by souffle::AstSemanticChecker::checkFact(), souffle::AstTranslator::ClauseTranslator::createValueIndex(), souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), and souffle::AstTranslator::ClauseTranslator::translateClause().
{
         return arguments[idx].get();
     }
getArguments()
std::vector<AstArgument*> souffle::AstAtom::getArguments () const inline
Provides access to the list of arguments of this atom.
Definition at line 88 of file AstLiteral.h.
References arguments, and souffle::toPtrVector().
Referenced by souffle::TypeAnalysis::analyseTypes(), souffle::applySips(), souffle::bindArguments(), souffle::AstSemanticChecker::checkAtom(), souffle::AstTranslator::ClauseTranslator::createValueIndex(), souffle::getBodyRelations(), souffle::getGroundedTerms(), souffle::getInlinedAtom(), souffle::getNextAtomMaxBoundSIPS(), souffle::getNextAtomMaxRatioSIPS(), souffle::hasBoundArgument(), souffle::isProposition(), souffle::makeInfoRelation(), souffle::numBoundArguments(), souffle::RemoveRelationCopiesTransformer::removeRelationCopies(), souffle::Adornment::run(), souffle::MagicSetTransformer::transform(), souffle::AstTranslator::ClauseTranslator::translateClause(), and souffle::unifyAtoms().
{
         return toPtrVector(arguments);
     }
getArity()
size_t souffle::AstAtom::getArity () const inline
Return the arity of the atom.
Definition at line 58 of file AstLiteral.h.
References arguments.
Referenced by souffle::areBijectivelyEquivalent(), souffle::AstSemanticChecker::checkAtom(), souffle::getNextAtomMaxRatioSIPS(), souffle::getSipsFunction(), souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::ReorderLiteralsTransformer::transform(), souffle::AstTranslator::ClauseTranslator::translateClause(), and souffle::AstTranslator::translateRelation().
{
         return arguments.size();
     }
getAtom()
const AstAtom* souffle::AstAtom::getAtom () const inline override virtual
Returns this class as the referenced atom.
Implements souffle::AstLiteral.
Definition at line 68 of file AstLiteral.h.
Referenced by souffle::getInlinedLiteral(), souffle::isValidMove(), souffle::makeInfoRelation(), souffle::negateLiteral(), and souffle::MagicSetTransformer::transform().
{
         return this;
     }
getChildNodes()
std::vector<const AstNode*> souffle::AstAtom::getChildNodes () const inline override virtual
Obtain a list of all embedded AST child nodes.
Reimplemented from souffle::AstNode.
Definition at line 128 of file AstLiteral.h.
References arguments.
{
         std::vector<const AstNode*> res;
         for (auto& cur : arguments) {
             res.push_back(cur.get());
         }
         return res;
     }
getName()
const AstRelationIdentifier& souffle::AstAtom::getName () const inline
Return the name of this atom.
Definition at line 53 of file AstLiteral.h.
References name.
Referenced by souffle::addAggregators(), souffle::addBackwardDependencies(), souffle::addForwardDependencies(), souffle::AstSemanticChecker::checkAtom(), souffle::AstSemanticChecker::checkFact(), souffle::AstSemanticChecker::checkInlining(), souffle::containsInlinedAtom(), souffle::formNegatedLiterals(), souffle::AuxiliaryArity::getArity(), souffle::getAtomRelation(), souffle::AstTranslator::getEvaluationArity(), souffle::getNextAtomMaxBoundSIPS(), souffle::getNextAtomNaiveSIPS(), souffle::isRecursiveClause(), souffle::isValidMove(), souffle::makeInfoRelation(), print(), souffle::reduceSingletonRelations(), souffle::AstProgram::removeClause(), souffle::RemoveRelationCopiesTransformer::removeRelationCopies(), souffle::Adornment::run(), souffle::ReduceExistentialsTransformer::transform(), souffle::ReorderLiteralsTransformer::transform(), souffle::MagicSetTransformer::transform(), souffle::AstTranslator::ClauseTranslator::translateClause(), and souffle::AstTranslator::translateRelation().
{
         return name;
     }
print()
void souffle::AstAtom::print (std::ostream & os) const inline override virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 97 of file AstLiteral.h.
References arguments, getName(), and i.
{
         os << getName() << "(";
         for (size_t i = 0; i < arguments.size(); ++i) {
             if (i != 0) {
                 os << ",";
             }
             if (arguments[i] != nullptr) {
                 arguments[i]->print(os);
             } else {
                 os << "_";
             }
         }
         os << ")";
     }
setArgument()
void souffle::AstAtom::setArgument (size_t idx, std::unique_ptr< AstArgument > newArg) inline
Replace the argument at the given index with the given argument.
Definition at line 83 of file AstLiteral.h.
References arguments.
Referenced by souffle::getInlinedAtom(), and souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries().
{
         arguments[idx].swap(newArg);
     }
setName()
void souffle::AstAtom::setName (const AstRelationIdentifier & n) inline
Set atom name.
Definition at line 63 of file AstLiteral.h.
References n, and name.
Referenced by souffle::separateDBs(), souffle::MagicSetTransformer::transform(), and souffle::AstTranslator::translateRecursiveRelation().
{
         name = n;
     }
Field Documentation
arguments
std::vector<std::unique_ptr<AstArgument> > souffle::AstAtom::arguments protected
Arguments of the atom.
Definition at line 147 of file AstLiteral.h.
Referenced by addArgument(), apply(), argSize(), clone(), equal(), getArgument(), getArguments(), getArity(), getChildNodes(), print(), and setArgument().
name
AstRelationIdentifier souffle::AstAtom::name protected
Name of the atom.
Definition at line 144 of file AstLiteral.h.
Referenced by clone(), equal(), getName(), and setName().
The documentation for this class was generated from the following file:
AstLiteral.h