souffle: souffle::AstUserDefinedFunctor Class Reference
souffle::AstUserDefinedFunctor Class Reference
User-Defined Functor.
#include <AstArgument.h>
Public Member Functions
AstUserDefinedFunctor ()=default
AstUserDefinedFunctor (std::string name, std::vector< std::unique_ptr< AstArgument >> args)
AstUserDefinedFunctor * clone () const override
Create clone.
const std::string & getName () const
get name
void print (std::ostream &os) const override
print user-defined functor
void setName (const std::string &name)
set name
Public Member Functions inherited from souffle::AstTerm
void add (std::unique_ptr< AstArgument > arg)
add argument to argument list
void apply (const AstNodeMapper &map) override
Apply the mapper to all child nodes.
AstArgument * getArg (const size_t idx) const
get argument at idx
std::vector< AstArgument * > getArguments () const
get arguments
size_t getArity () const
get number of arguments
std::vector< const AstNode * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
void setArg (const size_t idx, std::unique_ptr< AstArgument > arg)
set argument
Public Member Functions inherited from souffle::AstNode
AstNode ()=default
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
Protected Member Functions inherited from souffle::AstFunctor
AstFunctor ()=default
AstFunctor (std::vector< std::unique_ptr< AstArgument >> operands)
Protected Member Functions inherited from souffle::AstTerm
AstTerm ()=default
AstTerm (std::vector< std::unique_ptr< AstArgument >> operands)
Protected Attributes
std::string name
name of user-defined functor
Protected Attributes inherited from souffle::AstTerm
std::vector< std::unique_ptr< AstArgument > > args
Arguments.
Detailed Description
User-Defined Functor.
Definition at line 360 of file AstArgument.h.
Constructor & Destructor Documentation
AstUserDefinedFunctor() [1/2]
souffle::AstUserDefinedFunctor::AstUserDefinedFunctor () default
AstUserDefinedFunctor() [2/2]
souffle::AstUserDefinedFunctor::AstUserDefinedFunctor (std::string name, std::vector< std::unique_ptr< AstArgument >> args) inline
Definition at line 363 of file AstArgument.h.
             : AstFunctor(std::move(args)), name(std::move(name)){};
Member Function Documentation
clone()
AstUserDefinedFunctor* souffle::AstUserDefinedFunctor::clone () const inline override virtual
Create clone.
Implements souffle::AstArgument.
Definition at line 381 of file AstArgument.h.
References souffle::AstVariable::getName(), and souffle::AstNode::getSrcLoc().
Referenced by souffle::getInlinedArgument().
{
         auto res = new AstUserDefinedFunctor();
         for (auto& cur : args) {
             res->args.emplace_back(cur->clone());
         }
         res->setSrcLoc(getSrcLoc());
         res->setName(getName());
         return res;
     }
equal()
bool souffle::AstUserDefinedFunctor::equal (const AstNode & other) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstTerm.
Definition at line 392 of file AstArgument.h.
References souffle::AstTerm::equal(), and souffle::AstVariable::name.
{
         assert(nullptr != dynamic_cast<const AstUserDefinedFunctor*>(&node));
         const auto& other = static_cast<const AstUserDefinedFunctor&>(node);
         return name == other.name && AstFunctor::equal(node);
     }
getName()
const std::string& souffle::AstUserDefinedFunctor::getName () const inline
get name
Definition at line 372 of file AstArgument.h.
References souffle::AstVariable::name.
Referenced by souffle::TypeAnalysis::analyseTypes(), souffle::AstSemanticChecker::checkProgram(), and souffle::AstTranslator::translateValue().
{
         return name;
     }
print()
void souffle::AstUserDefinedFunctor::print (std::ostream & os) const inline override virtual
print user-defined functor
Implements souffle::AstNode.
Definition at line 367 of file AstArgument.h.
References souffle::join(), and souffle::AstVariable::name.
{
         os << '@' << name << "(" << join(args, ",", print_deref<std::unique_ptr<AstArgument>>()) << ")";
     }
setName()
void souffle::AstUserDefinedFunctor::setName (const std::string & name) inline
set name
Definition at line 377 of file AstArgument.h.
References souffle::AstVariable::name.
{
         this->name = name;
     }
Field Documentation
name
std::string souffle::AstUserDefinedFunctor::name protected
name of user-defined functor
Definition at line 399 of file AstArgument.h.
The documentation for this class was generated from the following file:
AstArgument.h